### ISSUE TITLE
Service call to netro watering service returns control before watering completes.

### ISSUE THREAD

**Issue by kenwiens** [kcofoni/ha-netro-watering#13]
I'm not sure if this is an issue or the way it's supposed to work by design.  I have an automation where I water one zone for 1 minute then water a different zone for 1 minute.  In the trace, the automation turns on the first zone and then 6 seconds later moves to the second zone (thus shutting down the first zone almost as quickly as it started.) it then runs the 2nd zone and moves on a few seconds later to the next step in the automation.  As that last step isn't a netro call - the second watering is allowed to continue.

I can get around this by setting the duration of the zone watering to 1 minute, then pausing the automation for 1 minute, and then watering the second zone. The work-around is simple - I'm just not sure if the service is supposed to work this way?

 
In case you are wondering why I would ever do this - I have 2 zones where the ground is slow to absorb water and most water runs off.  I want to water it for 1 minute, let is soak in for a minute and then water it again for a minute.  I'll put this in a loop to repeat about 15 times.  During the minute that I'm letting the water soak in, I'm watering the other zone for 1 minute (on and off).

Below is my test script - and attached is a screen shot of the trace.

alias: Netro - watering test
description: Test netro watering services
trigger: []
condition: []
action:
  - service: netro_watering.start_watering
    data:
      duration: 1
    target:
      entity_id: switch.netro_1_front_right_spruce_start_stop_watering
  - service: netro_watering.start_watering
    data:
      duration: 1
    target:
      entity_id: switch.netro_4_front_left_birch_start_stop_watering
  - service: light.toggle
    data: {}
    target:
      entity_id: light.master_bedroom_wall_switch_plug
mode: single

![trace](https://github.com/kcofoni/ha-netro-watering/assets/35972142/73cb8875-192f-4052-a58e-06058ce08172)

**Comment by kcofoni** [comment]
> I'm not sure if this is an issue or the way it's supposed to work by design. I have an automation where I water one zone for 1 minute then water a different zone for 1 minute. In the trace, the automation turns on the first zone and then 6 seconds later moves to the second zone (thus shutting down the first zone almost as quickly as it started.) it then runs the 2nd zone and moves on a few seconds later to the next step in the automation. As that last step isn't a netro call - the second watering is allowed to continue.
> 
> I can get around this by setting the duration of the zone watering to 1 minute, then pausing the automation for 1 minute, and then watering the second zone. The work-around is simple - I'm just not sure if the service is supposed to work this way?
> 
> In case you are wondering why I would ever do this - I have 2 zones where the ground is slow to absorb water and most water runs off. I want to water it for 1 minute, let is soak in for a minute and then water it again for a minute. I'll put this in a loop to repeat about 15 times. During the minute that I'm letting the water soak in, I'm watering the other zone for 1 minute (on and off).

Yes this is by design for sure:  requesting for an immediate irrigation of a zone should actually stop any on-going irrigation on another one, assuming that two zones cannot be watered at the same time. One could have imagined a queuing of requests but apparently this is not the expected behavior.

Luckily there is a simple way to do it the way you want. You should use the `delay `parameter of the watering service as illustrated below. 
```
service: netro_watering.start_watering
data:
  duration: 1
  delay: 2
target:
  entity_id: switch.well_start_stop_watering
```
So, you can, when running your automation, schedule
- the first watering right now for one minute to zone "z1"
- the next watering in one minute for one minute to "z2" and so on...
- the last watering in "n" minute for one minute to "zp"
 
The more elegant manner probably is to make a loop along your switches. Something like:
```
repeat:
  for_each:
    - well
    - indian_lilac
    - weeping_willow
  sequence:
    - service: netro_watering.start_watering
      data:
        duration: 1
        delay: repeat.index
      target:
        entity_id: "switch.{{ repeat.item }}_startstop_watering"
```
I guess it is better than being slept during in between the different watering phases.

**Comment by kenwiens** [comment]
The last option has an issue for me in that I only am watering 1 or 2 zones in this manner - not all of them.  I prefer the one you describe as the "more elegant"  :-)  However, I have 2 zones and I want to water 1 zone of 1 minute then the second zone for 1 minute - and repeat that sequence 15 times.  I suppose I could embed this code in another repeat loop (nested repeat loops).

Currently I am still using my code with the sleep function.  My reason for that was I am unsure how many water/delay sequences I can queue in the netro?  With 2 zones, and water / delay command for each, 15 times - that would be a total of 60 commands to queue to the netro.  Is there a limit here?

thanks for the ideas,
Ken
