### ISSUE TITLE
Errore in device definition with 2023.8.0

### ISSUE THREAD

**Issue by coserotondo** [kcofoni/ha-netro-watering#15]
Belo the log after updating to 2023.8.0:

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:624
Integration: Sensor (documentation, issues)
First occurred: 10:00:14 (24 occurrences)
Last logged: 10:06:10

Ignoring invalid device info: Invalid device info {'default_model': 'Pixie', 'default_name': 'Giardino', 'hw_version': '1.3', 'identifiers': {('netro_watering', '10521ce699a9')}, 'manufacturer': 'Netro', 'sw_version': '1.3.2'} for 'netro_watering' config entry: device info needs to either describe a device, link to existing device or provide extra information.
Ignoring invalid device info: Invalid device info {'default_model': 'Virtual zone', 'default_name': 'Giardino 1', 'identifiers': {('netro_watering', 'XXX')}, 'manufacturer': 'Netro', 'via_device': ('netro_watering', 'XXX')} for 'XXX' config entry: device info needs to either describe a device, link to existing device or provide extra information.

The device is no more in the dashboard but only the sensors.

**Comment by kcofoni** [comment]
Thanks for alerting. Fixed in QA, it should go live in a few hours.

**Comment by kcofoni** [comment]
Please apply https://github.com/kcofoni/ha-netro-watering/releases/tag/1.1.3
