### ISSUE TITLE
Lovelace cards yaml examples

### ISSUE THREAD

**Issue by Polosaz** [kcofoni/ha-netro-watering#18]
This is not an issue but a request to make the integration easier to use. Would it be possible to have the YAML configuration of the lovecards that you present as examples?

Thank you very much for the work to make this useful integration.

**Comment by kcofoni** [comment]
> This is not an issue but a request to make the integration easier to use. Would it be possible to have the YAML configuration of the lovecards that you present as examples?
> 
> 
> 
> Thank you very much for the work to make this useful integration.

https://github.com/kcofoni/ha-netro-watering/discussions/8
