### ISSUE TITLE
Integration Installation Failed in HA 2024.6.1

### ISSUE THREAD

**Issue by matapan** [kcofoni/ha-netro-watering#19]
Integration failed to install in HA 2024.6.1. 

Error log detail:
Logger: homeassistant.util.package
Source: util/package.py:123
First occurred: 4:43:22 PM (3 occurrences)
Last logged: 4:43:56 PM

Unable to install package requests==2.31.0: ERROR: Cannot install requests==2.31.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by lufetico** [comment]
Same error here.

**Comment by robertatc** [comment]
Yeap, same here.

**Comment by kcofoni** [comment]
Sorry for that. I will publish a new release tomorrow. In the meantime please edit the manifest.json file and set the version of "requests" to 2.32.3 and restart home assistant. I just did it and it is ok. 

![image](https://github.com/kcofoni/ha-netro-watering/assets/75487677/af38e42b-16db-49c0-bb1f-0ec7fef384af)

**Comment by robertatc** [comment]
Thanks @kcofoni 
Working from my side.

**Comment by lufetico** [comment]
Thanks @kcofoni 
It works!

**Comment by matapan** [comment]
Thank you @kcofoni

**Comment by kcofoni** [comment]
Please migrate to version 1.2.1 for compatibility with HA 2024.6.1
