### ISSUE TITLE
[Question] - How to push the next schedule irrigation

### ISSUE THREAD

**Issue by robertatc** [kcofoni/ha-netro-watering#21]
Hello,

Is not a issue at all, just a question. 

I've the latest version of the integration and it's working perfect.
I want to know if is possible to push the next schedule of my HomeAssistant automatiation in order to establish at what time is going to be the next irrigation at the dashboard that I've. 

If so, how can I do it? Thanks in advance. 

Kind Regards

**Comment by robertatc** [comment]
@kcofoni 

Not really. So I’ve two automations at Home Assistant. One at the morning and another one at night it, both of them starts the irrigation system. 

At netro’s calendar it only appears once the irrigation is about to start or starting, however, I want that before, like one day before or at 00:00 if that day.

Not sure if it’s possible or not.

Thanks for your time ☺️☺️☺️

**Comment by kcofoni** [comment]
OK. To do that I would simply run the `netro_watering.start_watering `service to plan my irrigation and you could integrate this service call in any automation that could run a couple of days before. Here is an example where I would plan to run the irrigation on next saturday at 11pm in a particular zone.

```
service: netro_watering.start_watering
target:
  device_id: df8dd8020050ec9623e5c76c721e2f9e
data:
  duration: 30
  start_time: "2024-07-06 23:00:00"
```

The `device_id `is referring to my target Netro zone (named `Puit `below).

As soon as you do that you may retrieve your plan in the netro dedicated calendar

![image](https://github.com/kcofoni/ha-netro-watering/assets/75487677/564a97d3-9dc6-4543-b5a6-e897ec840614)

Is that what you are expecting ?

**Comment by kcofoni** [comment]
I guess you have no more comment about this, so I close the issue.
