### ISSUE TITLE
issue " Netro (NPA) error occurred for this serial number"

### ISSUE THREAD

**Issue by emanueletruocchio** [kcofoni/ha-netro-watering#22]
I would like to start by saying that until this morning the integration worked perfectly. today in the afternoon it gave me an error on the serial number of my device and I decided to remove and install everything from scratch. it gives me this message when I try to enter the serial number of the control unit. How can I solve it?
Netro watering version 1.2.1, h.a. version 2024.7.3

![errore netro](https://github.com/user-attachments/assets/5fc412bc-d919-4607-8a9d-c2f79cf50f04)

**Comment by emanueletruocchio** [comment]
Solved, the tokens were out.

**Comment by emanueletruocchio** [comment]
Solved, the tokens were out

**Comment by kcofoni** [comment]
> Solved, the tokens were out

Glad to see it wasn't much. You can trigger an automation when the token reaches very low levels to prevent inconvenience. there is an entity indicating the number of tokens remaining. Have you looked in the log to see if the integration provided a more explicit message?
