### ISSUE TITLE
Netro API weather functions and negative values

### ISSUE THREAD

**Issue by kenwiens** [kcofoni/ha-netro-watering#24]
I am using the netro weather update calls.  I notice for temperature and dew point, these values cannot be below 0.  Is that an issue with the HA integration or with the API itself?  I am sending weather information every few hours, and in the early morning it can easily be below 0C.

I can modify my calls so that if the temp is below 0, to just send 0, but I wanted to confirm where this restriction actually lay.

![image](https://github.com/user-attachments/assets/d2639395-951c-45d6-bb28-5099151de1d8)

**Comment by kcofoni** [comment]
This is clearly a big mistake on my part. I limited the temperature range to the interval 0-60°C while the Netro API supports negative values ​​very well. I'll correct it but give me a few days, I'm particularly busy at the moment.
In the meantime, if you are in a hurry, you can work on the services.yaml file and the \_\_init\_\_.py file where the tolerance intervals appear for each report weather service parameter. I you edit those files and change them, you just have to restart ha and it is gonna be effective.

example:
`__init__.py:            vol.Coerce(float), vol.Range(min=-40, max=60)`
`services.yaml:          min: -40`
